version: 2.1

default:
  environment: &envvars
    RPC_REPO: github.com/redsift/go-sandbox-rpc
    RPC_REPO_COMMIT: e56484a
    CONTAINER_NAME: quay.io/redsift/sandbox-go
    CIRCLE_REVERSE_DEPENDENCIES: sandbox-go-rocksdb
executors:
  dockexec:
    shell: /bin/bash
    environment: *envvars
    docker:
      - image: cibuilds/docker:18.06.3-ce


commands:
  v_build:
    parameters:
      nv:
        type: string
      islatest:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run: ./circle/docker_build << parameters.nv >> << parameters.islatest >>
      - run: ./circle/gen_testing_dockerfile << parameters.nv >>
      - run: ./circle/docker_test << parameters.nv >>
      - persist_to_workspace:
          root: ./
          paths:
            - circle
      - deploy:
          command: docker push $CONTAINER_NAME

jobs:
  build_default:
    executor: dockexec
    steps:
      - v_build:
          nv: "1.10.8"

  build_11:
    executor: dockexec
    steps:
      - v_build:
          nv: "1.11.13"
  
  build_12:
    executor: dockexec
    steps:
      - v_build:
          nv: "1.12.14"

  build_13:
    executor: dockexec
    steps:
      - v_build:
          nv: "1.13.5"
          islatest: true

  trigger-builds:
    executor: dockexec
    steps:
      - attach_workspace:
          at: /
      - run: /circle/trigger_build

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_default
      - build_11
      - build_12
      - build_13
      - trigger-builds:
          requires:
            - build_default
          filters:
            branches:
              only:
                - master
