#!/bin/bash
set -eu

GV=$1
CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$GV$SUFFIX

cat << EOF > ./Dockerfile.testing
FROM ${imageName}
LABEL author="Christos Vontas"
LABEL email="christos@redsift.io"
LABEL version="1.0.1"

COPY --chown=7438:7438 testFixtures/sift /run/sandbox/sift
RUN /usr/bin/redsift/install ${TEST_NODES} && chown -R 7438:7438 /home/sandbox/.cache && chown -R 7438:7438 /run/sandbox/sift/server

EOF

